services:
  mkdocs:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs-material
    volumes:
      # mount your project root (must contain mkdocs.yml + docs/) into /docs
      - ./:/docs
    ports:
      - "8080:8000"
    command: >
      serve
      --dev-addr=0.0.0.0:8080
