site_name: "Bento Documentation"
site_dir: "build"

site_url: https://SanjeevLakhwani.github.io/bento-docs/
repo_url: https://github.com/SanjeevLakhwani/bento-docs

theme:
  name: "material"

plugins:
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ""
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
