name: 📚 Deploy MkDocs via mike - manual

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Which tag should I deploy?"
        required: true
        default: "v1.0.0"

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: true

      - run: git fetch origin gh-pages:gh-pages

      - name: Configure Git author
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi --no-root

      - name: mike deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run mike deploy "${{ github.event.inputs.tag }}" --push --allow-empty --deploy-prefix docs

      - name: mike alias
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run mike alias "${{ github.event.inputs.tag }}" latest --update-aliases --push

      - name: mike set-default
        run: |
          poetry run mike set-default latest
